### ISSUE TITLE
How to add my own buttons into each record?

### ISSUE THREAD

**Issue by win32nipuh** [gustavnavar/Grid.Blazor#109]
I have a grid: each record contains information about some document uploaded by user (in File system).

I'd like to add buttons or splitbutton to every record like:

<View>
<Download>
<Delete>

and corresponding reaction.

How I can do it?

**Comment by gustavnavar** [comment]
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Render_button_checkbox_etc_in_a_grid_cell.md

**Comment by gustavnavar** [comment]
Demo: https://gridblazor.azurewebsites.net/editrows

**Comment by win32nipuh** [comment]
Yes, sorry, now I see. Thnx.
Btw, is it possible to add my button (Component) in the razor like this:
```
 Action<IGridColumnCollection<S3Library>> columns = c =>
        {
            c.Add(o => o.DocName);
// --??
            c.Add(o => o.DocDate).Format("{0:yyyy-MM-dd}");
            c.Add(o => o.DocSize);
        };
```

**Comment by win32nipuh** [comment]
I am trying to add button. When I run the test app I receive:

```
'S3Blazor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.1\System.Runtime.Serialization.Primitives.dll'. 
Exception thrown: 'System.InvalidOperationException' in GridBlazor.dll
'S3Blazor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.1\System.Diagnostics.StackTrace.dll'. 
'S3Blazor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.1\System.Reflection.Metadata.dll'. 
'S3Blazor.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.1\System.Collections.Immutable.dll'. 
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: You need to specify render expression using RenderValueAs

System.InvalidOperationException: You need to specify render expression using RenderValueAs
   at GridBlazor.Columns.GridColumn`2.GetValue(T instance)
   at GridBlazor.Columns.GridColumn`2.GetCell(Object instance)
   at GridBlazor.Pages.GridCellComponent`1.OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit '4fx_ZYDN-aBrXKEEnGsAfCJkwxcQxEYIrOX4rewAB-A'.

```
Could you please say me: what do I incorrect?  


```
        public static Action<IGridColumnCollection<S3Library2>, object>
            S3Library2ColumnsWithEdit = (c, obj) =>
            {
                c.Add().Encoded(false).Sanitized(false).RenderComponentAs<ButtonCell>(obj);
                c.Add(o => o.KeyName).Titled("Name");
                c.Add(o => o.KeySize).Titled("Size");
                c.Add(o => o.Modified).Titled("Last Modified").SetWidth(250);
            };

```
```
protected override async Task OnParametersSetAsync()
    {
        var locale = CultureInfo.CurrentCulture;
        SharedResource.Culture = locale;

        Action<IGridColumnCollection<S3Library2>> columns = c =>
        ColumnCollections.S3Library2ColumnsWithEdit(c, "editrows");


        //Action<IGridColumnCollection<S3Library2>> columns = c =>
        //{
        //    c.Add(o => o.Bucket);
        //    c.Add(o => o.Prefix);
        //    c.Add(o => o.KeyName);
        //    //            c.Add(o => o.Modified, "DocDate").Format("{0:yyyy-MM-dd}");
        //    c.Add(o => o.Modified, "DocDate").Format("{0:yyyy-MM-dd}");
        //    c.Add(o => o.KeySize);
        //    //c.Add(o=>o.ETag).RenderComponentAs(typeof(ButtonCell));
        //    //c.Add(o => o.ETag);
        //};

        var query = new QueryDictionary<StringValues>();

        var client = new GridClient<S3Library2>(q => S3Service.GetS3LibraryGridRows(columns, q),query, false, "ordersGrid", columns, locale)
          .Sortable()
          .Filterable()
          .ClearFiltersButton(true)
          .Selectable(true, true)
          .Groupable(true)
          .Searchable(true, false, false)
          .SetStriped(true)
          .ChangePageSize(true)
          .WithMultipleFilters()
          .WithGridItemsCount();

        _grid = client.Grid;
        _task = client.UpdateGrid();
        await _task;
    }

```

**Comment by timbze** [comment]
@win32nipuh Can you share your ButtonCell code?

**Comment by Oleg26Dev** [comment]
Yes, that is:

```
@using S3Blazor.Models
@*@using S3Blazor.Columns*@
@implements ICustomGridComponent<S3Library2>
@inject NavigationManager NavigationManager

<button class='btn btn-sm btn-primary' @onclick="MyClickHandler">Edit</button>

@code {
    [Parameter]
    public S3Library2 Item { get; set; }

    [Parameter]
    public IList<Action<object>> Actions { get; set; }

    [Parameter]
    public CGrid<S3Library2> Grid { get; set; }

    [Parameter]
    public object Object { get; set; }

    private void MyClickHandler(MouseEventArgs e)
    {
        if (Actions == null)
        {
            string gridState = Grid.GetState();
            if (Object == null)
            {
                NavigationManager.NavigateTo($"/editorder/{Item.KeyName.ToString()}/gridsample/{gridState}");
            }
            else
            {
                string returnUrl = (string)Object;
                NavigationManager.NavigateTo($"/editorder/{Item.KeyName.ToString()}/{returnUrl}/{gridState}");
            }
        }
        else
        {
            Actions[0]?.Invoke(Item);
        }
    }
}

```

**Comment by timbze** [comment]
@win32nipuh I did look at your ButtonCell code but could not see something wrong yet. I had a similar error when I had wrong variable names in ButtonCell (e.g. I think GridBlazor requires it to be Item and Object (case sensitive)), but I think your's is right.

**Comment by win32nipuh** [comment]
After checking the ButtonCell code I have detected that it has parameters which I do not pass.
This issue can be closed.
