### ISSUE TITLE
System.Text.Json exception in GridBlazor 1.3.28

### ISSUE THREAD

**Issue by timbze** [gustavnavar/Grid.Blazor#120]
**I updated these 3 packages:**
GridBlazor from 1.3.24 to 1.3.28
GridMvcCore from 2.11.20 to 2.11.22
GridShared from 2.11.20 to 2.11.21

My project is on .net core 3.1.2

**And then I got this exception (can not load Grid at all):**
```
2020-03-04 07:34:18.0463|100|WARN|Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer+Log.UnhandledExceptionRenderingComponent|Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer|Unhandled exception rendering component: Could not load file or assembly 'System.Text.Json, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Text.Json, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at GridBlazor.Pages.GridHeaderComponent`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Additional**
Downgrading only GridBlazor to 1.3.27 makes it work again.

**Comment by gustavnavar** [comment]
It doesn't find the System.Text.Json assembly. Sometimes nuget install program doesn't install all dependencies. Can you upgrade GridBlazor to 1.3.28 again?

**Comment by timbze** [comment]
Didn't work. It turns out GridShared package System.Text.Json needs to be upgraded to 4.7.1 (I guess after other .net dependencies were upgraded)

**Comment by gustavnavar** [comment]
GridShared 2.11.22 has been uploaded. It includes System.Text.Json 4.7.1.
