### ISSUE TITLE
Error in RenderCrudComponentAs

### ISSUE THREAD

**Issue by trunovwdev** [gustavnavar/Grid.Blazor#246]
server-side grid

ColumnCollection with this code:

      c.Add(true, "CustomFieldName")
          .SetCrudHidden(false)
          // or .SetCrudHidden(false, true, false, false)
          .RenderCrudComponentAs<MyComponent>(false);
in Create mode returns an error:

System.ArgumentException: An item with the same key has already been added. Key: CustomFieldName
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at GridBlazor.Pages.GridCreateComponent`1.OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyCascadingValueChanged(ParameterViewLifetime& lifetime)
   at Microsoft.AspNetCore.Components.CascadingValue`1.NotifySubscribers(ParameterViewLifetime& lifetime)
   at Microsoft.AspNetCore.Components.CascadingValue`1.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.UpdateRetainedChildComponent(DiffContext& diffContext, Int32 oldComponentIndex, Int32 newComponentIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'umHtD_EIm5VFHzB1RUqxw4a1mZT2CfWn__7JxRJ6yjk'.

in View, Delete or Update mode all right

**Comment by gustavnavar** [comment]
I can not reproduce this error. But it seems that you have added 2 columns with the same name in the column definition. Can you remove the name the column definition?

```c#
 c.Add(true)
      .SetCrudHidden(false)
      // or .SetCrudHidden(false, true, false, false)
      .RenderCrudComponentAs<MyComponent>(false);
```
