### ISSUE TITLE
Call Razor Method from Button

### ISSUE THREAD

**Issue by dradovic** [gustavnavar/Grid.Blazor#8]
Is it possible to call a code-behind method from rendered html in a grid cell? Something like:

`column.Add().Encoded(false).Sanitized(false).RenderValueAs(o => $"<button onclick=\"@MyClickHandler({o.Id})\">...</button>");
`

**Comment by gustavnavar** [comment]
It's not possible.

I thiink it will be easier to add something like
```c#
column.Add().Encoded(false).Sanitized(false).RenderValueAs(o => $"...").Onclick(MyClickHandler()); 
```
Should it work for you?

**Comment by dradovic** [comment]
How would the click handler know, which row was clicked? In the `RenderValueAs`, I have `o`, so I can access `o.Id`.

**Comment by gustavnavar** [comment]
I think that the MyClickHandler() function that you will have write for the column definition must have the row item as parameter. You will have to write comething similar to:

```c#
    protected void MyClickHandler(object item)
    {
        long Id = ((Order)item).OrderId;
        ...
    } 
```

**Comment by dradovic** [comment]
Yes. That could work.

In general, this approach would mean that you would have to extend Grid.Blazor for every kind of event. This is just the click event.

What is the reason that Razor functions cannot be emitted directly?

**Comment by gustavnavar** [comment]
I have to use MarkupString to render html elements. And it does not suport rendering of components yet https://github.com/aspnet/Blazor/issues/1334

**Comment by dradovic** [comment]
I see. So are you considering to add a `OnClick` method?

**Comment by gustavnavar** [comment]
Yes, I am. At the end of next week I will try to implement a solution for this.

**Comment by gustavnavar** [comment]
I've found a different approach. Instead of only using MarkupString for rendering columns, I've added the option to render blazor components.

You can get info about this in the section ##Component columns## of https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Custom_columns.md

I've also upload a new nuget package (https://www.nuget.org/packages/GridBlazor/0.6.2) including component columns support.

**Comment by dradovic** [comment]
That sounds exactly like what we need!

I've just tried it out but unfortunately I get an error when starting the app:

> System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Method 'RenderComponentAs' in type 'GridMvc.Columns.GridColumn`2' from assembly 'GridMvc, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'RenderComponentAs' in type 'GridMvc.Columns.HiddenGridColumn`2' from assembly 'GridMvc, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionEndpointDataSource..ctor(IActionDescriptorCollectionProvider actions, ActionEndpointFactory endpointFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.EnsureRazorPagesServices(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.MapRazorPages(IEndpointRouteBuilder endpoints)
   at esme.Admin.Server.Startup.<>c.<Configure>b__3_0(IEndpointRouteBuilder endpoints) in C:\Users\DejanAppenzeller\source\repos\esme\src\esme.Admin.Server\Startup.cs:line 95

**Comment by gustavnavar** [comment]
You have to update the back-end GridMvcCore package to version 2.8.2 (https://www.nuget.org/packages/GridMvcCore/2.8.2).

If your solution use the GridShared package in the Shared project you must update it to version 2.8.2 (https://www.nuget.org/packages/GridShared/2.8.2)

**Comment by dradovic** [comment]
Yes. Works like a charm. Great job!
